# Generated by Django 5.2.13 on 2026-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='internship_logos/'),
        ),
    ]
